default: &default
  twitter:
    host: https://arcane-ravine-29792.herokuapp.com
    authorize_path: /oauth/authorize
    token_request_path: /oauth/token
    tweets_path: /api/tweets

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default